language: php

php:
  - 5.6
  - 7.0
  - hhvm

# This triggers builds to run on the new TravisCI infrastructure.
# See: http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

matrix:
  allow_failures:
    - php: 7.0
    - php: hhvm

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source
  - npm install
  - ./node_modules/.bin/phantomjs --webdriver=4444 --webdriver-loglevel=ALL &
  - php app/console server:run localhost:8000 &
  - sleep 1

script:
  - ./bin/behat

#    <!-- later or irrelevant, if not using phpunit for unit tests -->
#after_script:
#  - if [[ $TRAVIS_PHP_VERSION != 'hhvm' && $TRAVIS_PHP_VERSION != '7.0' ]]; then php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover; fi
