<?php

namespace Memy\MemeBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MemeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MemeRepository extends EntityRepository
{
}
